version: '3.8'
services:
  redmine:
    image: redmine
    container_name: redmine
    ports:
      - 8080:3000
    volumes:
      - vol_redmine:/usr/src/redmine/files
    environment:
      REDMINE_DB_MYSQL: redmine-db
      REDMINE_DB_PASSWORD: redminedb
    depends_on:
      - redmine-db
    restart: always
    
  redmine-db:
    image: mariadb
    container_name: redmine-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: redminedb
      MYSQL_DATABASE: redmine
    volumes:
      - vol_redmine_db:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
   
volumes:
  vol_redmine:
  vol_redmine_db:
